# **[1] Import Libraries**

In [ ]:
import io
import numpy as np
import pandas as pd
import seaborn as sns
from google.colab import files
import matplotlib.pyplot as plt

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

# **[2] Upload & Explore Data**

In [ ]:
uploaded = files.upload()

Saving Superstore.csv to Superstore.csv

In [ ]:
df = pd.read_csv('Superstore.csv', encoding='latin1')

In [ ]:
df.head()

   Row ID        Order ID  Order Date   Ship Date       Ship Mode Customer ID    Customer Name    Segment        Country             City       State  Postal Code Region       Product ID         Category Sub-Category                                       Product Name     Sales  Quantity  Discount    Profit
0     1.0  CA-2016-152156   11/8/2016  11/11/2016    Second Class    CG-12520      Claire Gute   Consumer  United States        Henderson    Kentucky      42420.0  South  FUR-BO-10001798        Furniture    Bookcases                  Bush Somerset Collection Bookcase  261.9600       2.0      0.00   41.9136
1     2.0  CA-2016-152156   11/8/2016  11/11/2016    Second Class    CG-12520      Claire Gute   Consumer  United States        Henderson    Kentucky      42420.0  South  FUR-CH-10000454        Furniture       Chairs  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400       3.0      0.00  219.5820
2     3.0  CA-2016-138688   6/12/2016   6/16/2016    Second Class    DV-13045  Darrin Van Huff  Corporate  United States      Los Angeles  California      90036.0   West  OFF-LA-10000240  Office Supplies       Labels  Self-Adhesive Address Labels for Typewriters b...   14.6200       2.0      0.00    6.8714
3     4.0  US-2015-108966  10/11/2015  10/18/2015  Standard Class    SO-20335   Sean O'Donnell   Consumer  United States  Fort Lauderdale     Florida      33311.0  South  FUR-TA-10000577        Furniture       Tables      Bretford CR4500 Series Slim Rectangular Table  957.5775       5.0      0.45 -383.0310
4     5.0  US-2015-108966  10/11/2015  10/18/2015  Standard Class    SO-20335   Sean O'Donnell   Consumer  United States  Fort Lauderdale     Florida      33311.0  South  OFF-ST-10000760  Office Supplies      Storage                     Eldon Fold 'N Roll Cart System   22.3680       2.0      0.20    2.5164

In [ ]:
df.tail()

      Row ID        Order ID Order Date Ship Date       Ship Mode Customer ID Customer Name   Segment        Country         City       State  Postal Code Region       Product ID         Category Sub-Category                                       Product Name    Sales  Quantity  Discount   Profit
9990  9991.0  CA-2017-121258  2/26/2017  3/3/2017  Standard Class    DB-13060   Dave Brooks  Consumer  United States   Costa Mesa  California      92627.0   West  FUR-FU-10000747        Furniture  Furnishings  Tenex B1-RE Series Chair Mats for Low Pile Car...   91.960       2.0       0.0  15.6332
9991  9992.0  CA-2017-121258  2/26/2017  3/3/2017  Standard Class    DB-13060   Dave Brooks  Consumer  United States   Costa Mesa  California      92627.0   West  TEC-PH-10003645       Technology       Phones                              Aastra 57i VoIP phone  258.576       2.0       0.2  19.3932
9992  9993.0  CA-2017-121258  2/26/2017  3/3/2017  Standard Class    DB-13060   Dave Brooks  Consumer  United States   Costa Mesa  California      92627.0   West  OFF-PA-10004041  Office Supplies        Paper  It's Hot Message Books with Stickers, 2 3/4" x 5"   29.600       4.0       0.0  13.3200
9993  9994.0  CA-2017-119914   5/4/2017  5/9/2017    Second Class    CC-12220  Chris Cortes  Consumer  United States  Westminster  California      92683.0   West  OFF-AP-10002684  Office Supplies   Appliances  Acco 7-Outlet Masterpiece Power Center, Wihtou...  243.160       2.0       0.0  72.9480
9994     NaN             NaN        NaN       NaN             NaN         NaN           NaN       NaN            NaN          NaN         NaN          NaN    NaN              NaN              NaN          NaN                                                NaN      NaN       NaN       NaN      NaN

In [ ]:
df.shape

(9995, 21)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9995 entries, 0 to 9994
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   float64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   float64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   float64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(6), object(15)
memory usage: 1.6+ MB

In [ ]:
df.isnull().sum()

Row ID           1
Order ID         1
Order Date       1
Ship Date        1
Ship Mode        1
Customer ID      1
Customer Name    1
Segment          1
Country          1
City             1
State            1
Postal Code      1
Region           1
Product ID       1
Category         1
Sub-Category     1
Product Name     1
Sales            1
Quantity         1
Discount         1
Profit           1
dtype: int64

In [ ]:
df.describe()

            Row ID   Postal Code         Sales     Quantity     Discount       Profit
count  9994.000000   9994.000000   9994.000000  9994.000000  9994.000000  9994.000000
mean   4997.500000  55190.379428    229.858001     3.789574     0.156203    28.656896
std    2885.163629  32063.693350    623.245101     2.225110     0.206452   234.260108
min       1.000000   1040.000000      0.444000     1.000000     0.000000 -6599.978000
25%    2499.250000  23223.000000     17.280000     2.000000     0.000000     1.728750
50%    4997.500000  56430.500000     54.490000     3.000000     0.200000     8.666500
75%    7495.750000  90008.000000    209.940000     5.000000     0.200000    29.364000
max    9994.000000  99301.000000  22638.480000    14.000000     0.800000  8399.976000

In [ ]:
print(f"Category: {df['Category'].unique()}")
print(f"Segment: {df['Segment'].unique()}")
print(f"Region: {df['Region'].unique()}")
print(f"Ship Mode: {df['Ship Mode'].unique()}")

Category: ['Furniture' 'Office Supplies' 'Technology' nan]
Segment: ['Consumer' 'Corporate' 'Home Office' nan]
Region: ['South' 'West' 'Central' 'East' nan]
Ship Mode: ['Second Class' 'Standard Class' 'First Class' 'Same Day' nan]

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df['Category'].value_counts()
df['Segment'].value_counts()
df['Region'].value_counts()

Region
West       3203
East       2848
Central    2323
South      1620
Name: count, dtype: int64

# **[3] Cleaning Data**

In [ ]:
df = df.dropna(how='all')
df.shape

(9994, 21)

In [ ]:
df['Order Date'] = pd.to_datetime(df['Order Date'], format='%m/%d/%Y')
df['Ship Date'] = pd.to_datetime(df['Ship Date'], format='%m/%d/%Y')

df[['Order Date', 'Ship Date']].dtypes

/tmp/ipython-input-96167847.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Order Date'] = pd.to_datetime(df['Order Date'], format='%m/%d/%Y')
/tmp/ipython-input-96167847.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Ship Date'] = pd.to_datetime(df['Ship Date'], format='%m/%d/%Y')

Order Date    datetime64[ns]
Ship Date     datetime64[ns]
dtype: object

In [ ]:
df['Order Year'] = df['Order Date'].dt.year

/tmp/ipython-input-3779288406.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Order Year'] = df['Order Date'].dt.year

In [ ]:
df[['Order Date', 'Order Year']].head()

  Order Date  Order Year
0 2016-11-08        2016
1 2016-11-08        2016
2 2016-06-12        2016
3 2015-10-11        2015
4 2015-10-11        2015

In [ ]:
df['Order Month'] = df['Order Date'].dt.month

/tmp/ipython-input-3752132757.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Order Month'] = df['Order Date'].dt.month

In [ ]:
df[['Order Date', 'Order Month', 'Order Year']].head()

  Order Date  Order Month  Order Year
0 2016-11-08           11        2016
1 2016-11-08           11        2016
2 2016-06-12            6        2016
3 2015-10-11           10        2015
4 2015-10-11           10        2015

In [ ]:
df['Shipping Duration'] = (df['Ship Date'] - df['Order Date']).dt.days

/tmp/ipython-input-2580384556.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Shipping Duration'] = (df['Ship Date'] - df['Order Date']).dt.days

In [ ]:
df[['Order Date', 'Ship Date', 'Shipping Duration']].head()

  Order Date  Ship Date  Shipping Duration
0 2016-11-08 2016-11-11                  3
1 2016-11-08 2016-11-11                  3
2 2016-06-12 2016-06-16                  4
3 2015-10-11 2015-10-18                  7
4 2015-10-11 2015-10-18                  7

In [ ]:
df['Profit Margin (%)'] = (df['Profit'] / df['Sales']) * 100

/tmp/ipython-input-2072452091.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Profit Margin (%)'] = (df['Profit'] / df['Sales']) * 100

In [ ]:
df[['Sales', 'Profit', 'Profit Margin (%)']].head()

      Sales    Profit  Profit Margin (%)
0  261.9600   41.9136              16.00
1  731.9400  219.5820              30.00
2   14.6200    6.8714              47.00
3  957.5775 -383.0310             -40.00
4   22.3680    2.5164              11.25

In [ ]:
df['Order Quarter'] = df['Order Date'].dt.quarter

/tmp/ipython-input-1988020648.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Order Quarter'] = df['Order Date'].dt.quarter

In [ ]:
df[['Order Date', 'Order Month', 'Order Year', 'Order Quarter']].head()

  Order Date  Order Month  Order Year  Order Quarter
0 2016-11-08           11        2016              4
1 2016-11-08           11        2016              4
2 2016-06-12            6        2016              2
3 2015-10-11           10        2015              4
4 2015-10-11           10        2015              4

In [ ]:
df['Order Month Name'] = df['Order Date'].dt.month_name()

/tmp/ipython-input-1566697757.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Order Month Name'] = df['Order Date'].dt.month_name()

In [ ]:
df['Profit Category'] = df['Profit Margin (%)'].apply(lambda x: 'High' if x > 30 else ('Low' if x < 0 else 'Medium'))

/tmp/ipython-input-2665250644.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Profit Category'] = df['Profit Margin (%)'].apply(lambda x: 'High' if x > 30 else ('Low' if x < 0 else 'Medium'))

In [ ]:
df['Return Flag'] = df['Profit'] < 0

/tmp/ipython-input-129684305.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Return Flag'] = df['Profit'] < 0

In [ ]:
def categorize_shipping(days):
    if days == 0:
        return 'Same Day'
    elif 1 <= days <= 2:
        return 'Fast'
    elif 3 <= days <= 5:
        return 'Standard'
    else:
        return 'Delayed'

df['Shipping Category'] = df['Shipping Duration'].apply(categorize_shipping)

/tmp/ipython-input-1740743248.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Shipping Category'] = df['Shipping Duration'].apply(categorize_shipping)

In [ ]:
df.head()

   Row ID        Order ID Order Date  Ship Date       Ship Mode Customer ID    Customer Name    Segment        Country             City       State  Postal Code Region       Product ID         Category Sub-Category                                       Product Name     Sales  Quantity  Discount    Profit  Order Year  Order Month  Shipping Duration  Profit Margin (%)  Order Quarter Order Month Name Profit Category  Return Flag Shipping Category
0     1.0  CA-2016-152156 2016-11-08 2016-11-11    Second Class    CG-12520      Claire Gute   Consumer  United States        Henderson    Kentucky      42420.0  South  FUR-BO-10001798        Furniture    Bookcases                  Bush Somerset Collection Bookcase  261.9600       2.0      0.00   41.9136        2016           11                  3              16.00              4         November          Medium        False          Standard
1     2.0  CA-2016-152156 2016-11-08 2016-11-11    Second Class    CG-12520      Claire Gute   Consumer  United States        Henderson    Kentucky      42420.0  South  FUR-CH-10000454        Furniture       Chairs  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400       3.0      0.00  219.5820        2016           11                  3              30.00              4         November          Medium        False          Standard
2     3.0  CA-2016-138688 2016-06-12 2016-06-16    Second Class    DV-13045  Darrin Van Huff  Corporate  United States      Los Angeles  California      90036.0   West  OFF-LA-10000240  Office Supplies       Labels  Self-Adhesive Address Labels for Typewriters b...   14.6200       2.0      0.00    6.8714        2016            6                  4              47.00              2             June            High        False          Standard
3     4.0  US-2015-108966 2015-10-11 2015-10-18  Standard Class    SO-20335   Sean O'Donnell   Consumer  United States  Fort Lauderdale     Florida      33311.0  South  FUR-TA-10000577        Furniture       Tables      Bretford CR4500 Series Slim Rectangular Table  957.5775       5.0      0.45 -383.0310        2015           10                  7             -40.00              4          October             Low         True           Delayed
4     5.0  US-2015-108966 2015-10-11 2015-10-18  Standard Class    SO-20335   Sean O'Donnell   Consumer  United States  Fort Lauderdale     Florida      33311.0  South  OFF-ST-10000760  Office Supplies      Storage                     Eldon Fold 'N Roll Cart System   22.3680       2.0      0.20    2.5164        2015           10                  7              11.25              4          October          Medium        False           Delayed

In [ ]:
new_column_order = [
    # المعرّفات
    'Row ID',

    # معلومات الطلب
    'Order ID', 'Order Date', 'Order Year', 'Order Quarter', 'Order Month', 'Order Month Name',
    'Ship Date', 'Shipping Duration', 'Shipping Category', 'Ship Mode',

    # معلومات العميل
    'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region',

    # معلومات المنتج
    'Product ID', 'Product Name', 'Category', 'Sub-Category',

    # المقاييس المالية
    'Sales', 'Quantity', 'Discount', 'Profit', 'Profit Margin (%)', 'Profit Category', 'Return Flag'
]

In [ ]:
df = df[new_column_order]
df.head()

   Row ID        Order ID Order Date  Order Year  Order Quarter  Order Month Order Month Name  Ship Date  Shipping Duration Shipping Category       Ship Mode Customer ID    Customer Name    Segment        Country             City       State  Postal Code Region       Product ID                                       Product Name         Category Sub-Category     Sales  Quantity  Discount    Profit  Profit Margin (%) Profit Category  Return Flag
0     1.0  CA-2016-152156 2016-11-08        2016              4           11         November 2016-11-11                  3          Standard    Second Class    CG-12520      Claire Gute   Consumer  United States        Henderson    Kentucky      42420.0  South  FUR-BO-10001798                  Bush Somerset Collection Bookcase        Furniture    Bookcases  261.9600       2.0      0.00   41.9136              16.00          Medium        False
1     2.0  CA-2016-152156 2016-11-08        2016              4           11         November 2016-11-11                  3          Standard    Second Class    CG-12520      Claire Gute   Consumer  United States        Henderson    Kentucky      42420.0  South  FUR-CH-10000454  Hon Deluxe Fabric Upholstered Stacking Chairs,...        Furniture       Chairs  731.9400       3.0      0.00  219.5820              30.00          Medium        False
2     3.0  CA-2016-138688 2016-06-12        2016              2            6             June 2016-06-16                  4          Standard    Second Class    DV-13045  Darrin Van Huff  Corporate  United States      Los Angeles  California      90036.0   West  OFF-LA-10000240  Self-Adhesive Address Labels for Typewriters b...  Office Supplies       Labels   14.6200       2.0      0.00    6.8714              47.00            High        False
3     4.0  US-2015-108966 2015-10-11        2015              4           10          October 2015-10-18                  7           Delayed  Standard Class    SO-20335   Sean O'Donnell   Consumer  United States  Fort Lauderdale     Florida      33311.0  South  FUR-TA-10000577      Bretford CR4500 Series Slim Rectangular Table        Furniture       Tables  957.5775       5.0      0.45 -383.0310             -40.00             Low         True
4     5.0  US-2015-108966 2015-10-11        2015              4           10          October 2015-10-18                  7           Delayed  Standard Class    SO-20335   Sean O'Donnell   Consumer  United States  Fort Lauderdale     Florida      33311.0  South  OFF-ST-10000760                     Eldon Fold 'N Roll Cart System  Office Supplies      Storage   22.3680       2.0      0.20    2.5164              11.25          Medium        False

In [ ]:
sales_profit_by_year = df.groupby('Order Year')[['Sales', 'Profit']].sum()
sales_profit_by_year

                  Sales      Profit
Order Year
2014        484247.4981  49543.9741
2015        470532.5090  61618.6037
2016        609205.5980  81795.1743
2017        733215.2552  93439.2696

In [ ]:
profit_by_category = df.groupby('Category')['Profit'].sum().sort_values(ascending=False)
profit_by_category

Category
Technology         145454.9481
Office Supplies    122490.8008
Furniture           18451.2728
Name: Profit, dtype: float64

In [ ]:
losses_by_category = df[df['Return Flag'] == True].groupby('Category').size()
losses_by_category

Category
Furniture          714
Office Supplies    886
Technology         271
dtype: int64

In [ ]:
# إجمالي عدد الصفوف في كل فئة
total_by_category = df['Category'].value_counts()

# عدد الخسائر في كل فئة (لديكها بالفعل)
losses_by_category = df[df['Return Flag'] == True].groupby('Category').size()

# حساب نسبة الخسارة
loss_percentage = (losses_by_category / total_by_category) * 100
loss_percentage.sort_values(ascending=False)

Category
Furniture          33.663366
Office Supplies    14.702954
Technology         14.672442
dtype: float64

In [ ]:
# تصدير البيانات إلى ملف Excel
df.to_excel('Superstore_Cleaned.xlsx', index=False)

# تحميل الملف في Google Colab (لتنزيله على جهازك)
from google.colab import files
files.download('Superstore_Cleaned.xlsx')